name: Wistia Data Ingestion CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

       # --- Deploy Lambda Functions ---
      - name: Create and deploy wistia-data-ingestion-lambda package
        run: |
          # Change directory to the Lambda function's folder
          cd data_ingestion
          # Create a deployment package including the code and dependencies
          zip -r lambda_function.zip . -x "*.DS_Store" "*.git/*"
          aws lambda update-function-code \
            --function-name wistia-data-ingestion \
            --zip-file fileb://lambda_function.zip

      - name: Create and deploy data-preprocessing package
        run: |
          # Change directory to the Lambda function's folder
          cd data_preprocessing
          # Create a deployment package including the code and dependencies
          zip -r lambda_function.zip . -x "*.DS_Store" "*.git/*"
          aws lambda update-function-code \
            --function-name wistia_data_processing \
            --zip-file fileb://lambda_function.zip

      # --- Update Glue Jobs ---
      # This step copies the Glue job scripts to S3 before updating the Glue jobs.
      - name: Upload Glue scripts to S3
        run: |
          aws s3 cp data_transformation/data_transformation_job.py s3://${{ secrets.S3_BUCKET_NAME }}/scripts/
          aws s3 cp data_joining/data_joining_job.py s3://${{ secrets.S3_BUCKET_NAME }}/scripts/

      - name: Update Glue Data Transformation Job
        run: |
          aws glue update-job \
            --job-name data_transformation_job.py \
            --job-update "{\"Command\":{\"Name\":\"glueetl\",\"ScriptLocation\":\"s3://${{ secrets.S3_BUCKET_NAME }}/scripts/data_transformation_job.py\"}}"

      - name: Update Glue Data Joining Job
        run: |
          aws glue update-job \
            --job-name data_joining_job.py \
            --job-update "{\"Command\":{\"Name\":\"glueetl\",\"ScriptLocation\":\"s3://${{ secrets.S3_BUCKET_NAME }}/scripts/data_joining_job.py\"}}"
